package cz.justarrived;

public interface Constants {

  String REACHED_DESTINATION_KEY = "REACHED_DESTINATION?";
  String REACHED_DESTINATION_IN_TIME_KEY = "REACHED_DESTINATION_IN_TIME";
  String DEFAULT_DISTANCE_THRESHOLD = "20";
  String SERVICE_RUNNING_KEY = "SERVICE_RUNNING";
  String LATEST_TEXT_KEY = "LATEST_TEXT";
  String LATEST_NAME_KEY = "LATEST_NAME";
  String LATEST_NUMBER_KEY = "LATEST_NUMBER";
  String SMS_OR_NOTIFY_KEY = "SMS_OR_NOTIFY";
  String TRIGGER_RADIUS_KEY = "TRIGGER_RADIUS";
  String CHOSEN_LOCATION_CAMERA_LAT = "CHOSEN_CAMERA_LAT";
  String CHOSEN_LOCATION_CAMERA_LNG = "CHOSEN_CAMERA_LNG";
  String MY_LOCATION = "MY_LOCATION";
  String DATABASE_NAME = "JustArrivedDB";

  float DEFAULT_CAMERA_ZOOM = 13f;
  float DEFAULT_CAMERA_TILT = 0f;
  float DEFAULT_CAMERA_BEARING = 0f;

  int REQUEST_SMS_SEND_PERMISSION = 1;
  int REQUEST_READ_CONTACTS_PERMISSION = 2;
  int REQUEST_ACCESS_FINE_LOCATION = 3;
  int DATABASE_VERSION = 1;

  String FIRST_RUN = "FIRST_RUN";
}
